<a href="https://colab.research.google.com/github/aryas-droid/Data-Acquisition-CaseStudy-Arya/blob/main/DataAcquisition_CaseStudy_Arya.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Part A – Data Extraction
Task 1
Read the Population dataset from the CSV file.

In [ ]:
import pandas as pd
print(pd.__version__)

2.2.3

In [7]:
import pandas as pd
pop=pd.read_csv("/content/drive/MyDrive/DSAB13/Class Activity/Data_Acquisition_CaseStudy/population[1].csv")
pop

           country  population
0    United States   331002651
1            China  1411778724
2            India  1380004385
3            Japan   125836021
4          Germany    83240525
5   United Kingdom    67886011
6           France    65273511
7            Italy    60461826
8           Canada    38005238
9        Australia    25687041
10          Brazil   212559417
11          Russia   145934462
12     South Korea    51780579
13           Spain    46754778
14          Mexico   128932753
15       Indonesia   273523615
16    Saudi Arabia    34813871
17          Turkey    84339067
18    South Africa    59308690
19       Argentina    45195774
20     Netherlands    17441139
21     Switzerland     8654622
22          Sweden    10353442
23          Norway     5421241
24       Singapore     5850342

In [8]:
#Display the first five rows.
print("First five rows: ",pop.head(6))
print("Shape :", pop.shape)
print("Datatypes: ",pop.dtypes)

First five rows:            country  population
0   United States   331002651
1           China  1411778724
2           India  1380004385
3           Japan   125836021
4         Germany    83240525
5  United Kingdom    67886011
Shape : (25, 2)
Datatypes:  country       object
population     int64
dtype: object

Task 2
Read the GDP dataset from the Excel file.
Hint:
● Use the appropriate pandas function.
● Display column names and data types.

In [9]:
import pandas as pd
gd=pd.read_excel("/content/drive/MyDrive/DSAB13/Class Activity/Data_Acquisition_CaseStudy/gdp[1].xlsx")
gd

           Country       GDP
0    United States  30500000
1            China  19230000
2            India   4187000
3            Japan   4180000
4          Germany   4744000
5   United Kingdom   3839000
6           France   3211000
7            Italy   2420000
8           Canada   2250000
9        Australia   1880000
10          Brazil   2330000
11          Russia   2200000
12     South Korea   1800000
13           Spain   1710000
14          Mexico   1810000
15       Indonesia   1500000
16    Saudi Arabia   1100000
17          Turkey   1350000
18    South Africa    410000
19       Argentina    640000
20     Netherlands   1150000
21     Switzerland    940000
22          Sweden    650000
23          Norway    580000
24       Singapore    530000

In [10]:
#Use the appropriate pandas function
print("Columns: ",gd.columns)

Columns:  Index(['Country', 'GDP'], dtype='object')

In [12]:
print("Shape: ",gd.shape)

Shape:  (25, 2)

In [11]:
gd.size

50

In [13]:
gd.head()

         Country       GDP
0  United States  30500000
1          China  19230000
2          India   4187000
3          Japan   4180000
4        Germany   4744000

In [14]:
gd.describe()

                GDP
count  2.500000e+01
mean   3.805640e+06
std    6.657691e+06
min    4.100000e+05
25%    1.100000e+06
50%    1.810000e+06
75%    3.211000e+06
max    3.050000e+07

In [15]:
gd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  25 non-null     object
 1   GDP      25 non-null     int64
dtypes: int64(1), object(1)
memory usage: 532.0+ bytes

In [16]:
gd.tail()

        Country      GDP
20  Netherlands  1150000
21  Switzerland   940000
22       Sweden   650000
23       Norway   580000
24    Singapore   530000

In [17]:
#Display column names and data types
gd.dtypes

Country    object
GDP         int64
dtype: object

In [ ]:
gd.columns

Index(['Country', 'GDP'], dtype='object')

Task 3
Read the Internet Users dataset from the JSON file.
Hint:
● Use either the json module or pandas.
● Convert the data into a DataFrame.

In [18]:
import pandas as pd
iu=pd.read_json("/content/drive/MyDrive/DSAB13/Class Activity/Data_Acquisition_CaseStudy/internet_users[1].json")
iu

           country  internet_users
0    United States       312000000
1            China      1080000000
2            India       850000000
3            Japan       118000000
4          Germany        79000000
5   United Kingdom        66000000
6           France        62000000
7            Italy        56000000
8           Canada        36000000
9        Australia        24000000
10          Brazil       181000000
11          Russia       125000000
12     South Korea        50000000
13           Spain        44000000
14          Mexico       102000000
15       Indonesia       212000000
16    Saudi Arabia        34000000
17          Turkey        69000000
18    South Africa        43000000
19       Argentina        41000000
20     Netherlands        17000000
21     Switzerland         8500000
22          Sweden        10100000
23          Norway         5300000
24       Singapore         5600000

In [19]:
# Use either the json module or pandas
import pandas as pd
iu=pd.read_json("/content/drive/MyDrive/DSAB13/Class Activity/Data_Acquisition_CaseStudy/internet_users[1].json")
iu

           country  internet_users
0    United States       312000000
1            China      1080000000
2            India       850000000
3            Japan       118000000
4          Germany        79000000
5   United Kingdom        66000000
6           France        62000000
7            Italy        56000000
8           Canada        36000000
9        Australia        24000000
10          Brazil       181000000
11          Russia       125000000
12     South Korea        50000000
13           Spain        44000000
14          Mexico       102000000
15       Indonesia       212000000
16    Saudi Arabia        34000000
17          Turkey        69000000
18    South Africa        43000000
19       Argentina        41000000
20     Netherlands        17000000
21     Switzerland         8500000
22          Sweden        10100000
23          Norway         5300000
24       Singapore         5600000

In [20]:
#Convert the data into a DataFrame.
iu=pd.DataFrame(iu)
iu

           country  internet_users
0    United States       312000000
1            China      1080000000
2            India       850000000
3            Japan       118000000
4          Germany        79000000
5   United Kingdom        66000000
6           France        62000000
7            Italy        56000000
8           Canada        36000000
9        Australia        24000000
10          Brazil       181000000
11          Russia       125000000
12     South Korea        50000000
13           Spain        44000000
14          Mexico       102000000
15       Indonesia       212000000
16    Saudi Arabia        34000000
17          Turkey        69000000
18    South Africa        43000000
19       Argentina        41000000
20     Netherlands        17000000
21     Switzerland         8500000
22          Sweden        10100000
23          Norway         5300000
24       Singapore         5600000

**TASK-4**

Read the Literacy Rate dataset from the XML file.
Hint:
● Use xml.etree.ElementTree or pandas.read_xml().
● Extract all required fields into a DataFrame.

In [21]:
import pandas as pd
lr=pd.read_xml("/content/drive/MyDrive/DSAB13/Class Activity/Data_Acquisition_CaseStudy/literacy_rate[1].xml")
lr

              name  literacy_rate
0    United States           99.0
1            China           97.2
2            India           77.7
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

PART-B
TASK-5

Explore each dataset.
Find the following:
● Number of rows
● Number of columns
● Column names
● Data types
● Missing values
● Duplicate records

In [23]:
print("Population")
print("Row and columns",pop.shape)
print("Column names",pop.columns)
print("______________________________________")
print("Data types",pop.dtypes)
print("______________________________________")
print("Missing values",pop.isnull().sum())
print("______________________________________")
print("Duplicate records",pop.duplicated().sum)

Population
Row and columns (25, 2)
Column names Index(['country', 'population'], dtype='object')
______________________________________
Data types country       object
population     int64
dtype: object
______________________________________
Missing values country       0
population    0
dtype: int64
______________________________________
Duplicate records <bound method Series.sum of 0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
dtype: bool>

In [24]:
print("GDP")
print("Row and columns",gd.shape)
print("Column names",gd.columns)
print("______________________________________")
print("Data types",gd.dtypes)
print("______________________________________")
print("Missing values",gd.isnull().sum())
print("______________________________________")
print("Duplicate records",gd.duplicated().sum)

GDP
Row and columns (25, 2)
Column names Index(['Country', 'GDP'], dtype='object')
______________________________________
Data types Country    object
GDP         int64
dtype: object
______________________________________
Missing values Country    0
GDP        0
dtype: int64
______________________________________
Duplicate records <bound method Series.sum of 0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
dtype: bool>

In [25]:
print("Internet Users")
print("Row and columns",iu.shape)
print("Column names",iu.columns)
print("______________________________________")
print("Data types",iu.dtypes)
print("______________________________________")
print("Missing values",iu.isnull().sum())
print("______________________________________")
print("Duplicate records",iu.duplicated().sum)

Internet Users
Row and columns (25, 2)
Column names Index(['country', 'internet_users'], dtype='object')
______________________________________
Data types country           object
internet_users     int64
dtype: object
______________________________________
Missing values country           0
internet_users    0
dtype: int64
______________________________________
Duplicate records <bound method Series.sum of 0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
dtype: bool>

In [26]:
print("Literacy Rate")
print("Row and columns",lr.shape)
print("Column names",lr.columns)
print("______________________________________")
print("Data types",lr.dtypes)
print("______________________________________")
print("Missing values",lr.isnull().sum())
print("______________________________________")
print("Duplicate records",lr.duplicated().sum)

Literacy Rate
Row and columns (25, 2)
Column names Index(['name', 'literacy_rate'], dtype='object')
______________________________________
Data types name              object
literacy_rate    float64
dtype: object
______________________________________
Missing values name             0
literacy_rate    0
dtype: int64
______________________________________
Duplicate records <bound method Series.sum of 0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
dtype: bool>

PART-C DATA TRANFORMATION

TASK-6
Rename columns wherever necessary so that all datasets have a common column
name for merging.
Hint:
● Example: Country → country

In [47]:
print("Population")
c=pop.rename(columns={"country":"country"})
c

Population

           country  population
0    United States   331002651
1            China  1411778724
2            India  1380004385
3            Japan   125836021
4          Germany    83240525
5   United Kingdom    67886011
6           France    65273511
7            Italy    60461826
8           Canada    38005238
9        Australia    25687041
10          Brazil   212559417
11          Russia   145934462
12     South Korea    51780579
13           Spain    46754778
14          Mexico   128932753
15       Indonesia   273523615
16    Saudi Arabia    34813871
17          Turkey    84339067
18    South Africa    59308690
19       Argentina    45195774
20     Netherlands    17441139
21     Switzerland     8654622
22          Sweden    10353442
23          Norway     5421241
24       Singapore     5850342

In [48]:
print("GDP")
d=gd.rename(columns={"Country":"country"})
d

GDP

           country       GDP
0    United States  30500000
1            China  19230000
2            India   4187000
3            Japan   4180000
4          Germany   4744000
5   United Kingdom   3839000
6           France   3211000
7            Italy   2420000
8           Canada   2250000
9        Australia   1880000
10          Brazil   2330000
11          Russia   2200000
12     South Korea   1800000
13           Spain   1710000
14          Mexico   1810000
15       Indonesia   1500000
16    Saudi Arabia   1100000
17          Turkey   1350000
18    South Africa    410000
19       Argentina    640000
20     Netherlands   1150000
21     Switzerland    940000
22          Sweden    650000
23          Norway    580000
24       Singapore    530000

In [49]:
r=iu.rename(columns={"Country":"country"})
r

           country  internet_users
0    United States       312000000
1            China      1080000000
2            India       850000000
3            Japan       118000000
4          Germany        79000000
5   United Kingdom        66000000
6           France        62000000
7            Italy        56000000
8           Canada        36000000
9        Australia        24000000
10          Brazil       181000000
11          Russia       125000000
12     South Korea        50000000
13           Spain        44000000
14          Mexico       102000000
15       Indonesia       212000000
16    Saudi Arabia        34000000
17          Turkey        69000000
18    South Africa        43000000
19       Argentina        41000000
20     Netherlands        17000000
21     Switzerland         8500000
22          Sweden        10100000
23          Norway         5300000
24       Singapore         5600000

In [50]:
s=lr.rename(columns={"name":"country"})
s

           country  literacy_rate
0    United States           99.0
1            China           97.2
2            India           77.7
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

In [51]:
# Convert required columns to numeric data types
# Convert required columns to numeric data types
pop["population"] = pd.to_numeric(pop["population"], errors="coerce")
gd["GDP"] = pd.to_numeric(gd["GDP"], errors="coerce")
iu["internet_users"] = pd.to_numeric(iu["internet_users"], errors="coerce")
lr["literacy_rate"] = pd.to_numeric(lr["literacy_rate"], errors="coerce")

print(pop.dtypes)
print(gd.dtypes)
print(iu.dtypes)
print(lr.dtypes)

country       object
population     int64
dtype: object
Country    object
GDP         int64
dtype: object
country           object
internet_users     int64
dtype: object
name              object
literacy_rate    float64
dtype: object

# Task 8
Merge all four datasets into one DataFrame.
Hint:
● Use the common column (country)
● Choose an appropriate join method.

In [52]:
merged_pop=c.merge(d,on="country",how="inner")
merged_pop=merged_pop.merge(r,on="country",how="inner")
merged_pop=merged_pop.merge(s,on="country",how="inner")
print(merged_pop)

           country  population       GDP  internet_users  literacy_rate
0    United States   331002651  30500000       312000000           99.0
1            China  1411778724  19230000      1080000000           97.2
2            India  1380004385   4187000       850000000           77.7
3            Japan   125836021   4180000       118000000           99.0
4          Germany    83240525   4744000        79000000           99.0
5   United Kingdom    67886011   3839000        66000000           99.0
6           France    65273511   3211000        62000000           99.0
7            Italy    60461826   2420000        56000000           99.0
8           Canada    38005238   2250000        36000000           99.0
9        Australia    25687041   1880000        24000000           99.0
10          Brazil   212559417   2330000       181000000           93.2
11          Russia   145934462   2200000       125000000           99.7
12     South Korea    51780579   1800000        50000000           98.8
13           Spain    46754778   1710000        44000000           98.6
14          Mexico   128932753   1810000       102000000           95.4
15       Indonesia   273523615   1500000       212000000           96.0
16    Saudi Arabia    34813871   1100000        34000000           97.3
17          Turkey    84339067   1350000        69000000           96.7
18    South Africa    59308690    410000        43000000           95.0
19       Argentina    45195774    640000        41000000           99.1
20     Netherlands    17441139   1150000        17000000           99.0
21     Switzerland     8654622    940000         8500000           99.0
22          Sweden    10353442    650000        10100000           99.0
23          Norway     5421241    580000         5300000          100.0
24       Singapore     5850342    530000         5600000           97.5

#Task 9
Create the following calculated columns:
1. Internet Penetration (%)
2. GDP Per Capita
Hint:
Round the calculated values to two decimal places.

In [54]:
# Task 9: Create calculated columns

# Internet Penetration (%)
merged_pop["Internet Penetration (%)"] = (
    merged_pop["internet_users"] / merged_pop["population"] * 100
).round(2)

# GDP Per Capita
merged_pop["GDP Per Capita"] = (
    merged_pop["GDP"] / merged_pop["population"]
).round(2)

# Display the result
print(merged_pop)

           country  population       GDP  internet_users  literacy_rate  \
0    United States   331002651  30500000       312000000           99.0
1            China  1411778724  19230000      1080000000           97.2
2            India  1380004385   4187000       850000000           77.7
3            Japan   125836021   4180000       118000000           99.0
4          Germany    83240525   4744000        79000000           99.0
5   United Kingdom    67886011   3839000        66000000           99.0
6           France    65273511   3211000        62000000           99.0
7            Italy    60461826   2420000        56000000           99.0
8           Canada    38005238   2250000        36000000           99.0
9        Australia    25687041   1880000        24000000           99.0
10          Brazil   212559417   2330000       181000000           93.2
11          Russia   145934462   2200000       125000000           99.7
12     South Korea    51780579   1800000        50000000           98.8
13           Spain    46754778   1710000        44000000           98.6
14          Mexico   128932753   1810000       102000000           95.4
15       Indonesia   273523615   1500000       212000000           96.0
16    Saudi Arabia    34813871   1100000        34000000           97.3
17          Turkey    84339067   1350000        69000000           96.7
18    South Africa    59308690    410000        43000000           95.0
19       Argentina    45195774    640000        41000000           99.1
20     Netherlands    17441139   1150000        17000000           99.0
21     Switzerland     8654622    940000         8500000           99.0
22          Sweden    10353442    650000        10100000           99.0
23          Norway     5421241    580000         5300000          100.0
24       Singapore     5850342    530000         5600000           97.5

    Internet Penetration (%)  GDP Per Capita
0                      94.26            0.09
1                      76.50            0.01
2                      61.59            0.00
3                      93.77            0.03
4                      94.91            0.06
5                      97.22            0.06
6                      94.98            0.05
7                      92.62            0.04
8                      94.72            0.06
9                      93.43            0.07
10                     85.15            0.01
11                     85.65            0.02
12                     96.56            0.03
13                     94.11            0.04
14                     79.11            0.01
15                     77.51            0.01
16                     97.66            0.03
17                     81.81            0.02
18                     72.50            0.01
19                     90.72            0.01
20                     97.47            0.07
21                     98.21            0.11
22                     97.55            0.06
23                     97.76            0.11
24                     95.72            0.09

#Part D – Load Data
#Task 10
Create a SQLite database. Store the final merged dataset into a table named
‘country_statistics’
Hint:
● Use the sqlite3 library.
● Load the DataFrame using pandas.

In [57]:
import sqlite3

# Create SQLite database
conn = sqlite3.connect("country_statistics.db")

# Store the final merged DataFrame into SQLite
merged_pop.to_sql(
    "country_statistics",
    conn,
    if_exists="replace",
    index=False
)

print("Data successfully stored in SQLite database.")

Data successfully stored in SQLite database.

#Task 11
Verify that the data has been loaded successfully.
Hint:
Retrieve the first five records from the SQLite table.

In [58]:
# Retrieve first five records from SQLite table

result = pd.read_sql_query(
    "SELECT * FROM country_statistics LIMIT 5",
    conn
)

print(result)

         country  population       GDP  internet_users  literacy_rate  \
0  United States   331002651  30500000       312000000           99.0
1          China  1411778724  19230000      1080000000           97.2
2          India  1380004385   4187000       850000000           77.7
3          Japan   125836021   4180000       118000000           99.0
4        Germany    83240525   4744000        79000000           99.0

   Internet Penetration (%)  GDP Per Capita
0                     94.26            0.09
1                     76.50            0.01
2                     61.59            0.00
3                     93.77            0.03
4                     94.91            0.06

#Part E – Data Analysis Using Pandas
#Answer the following questions using pandas.
1 List the Top 5 countries by GDP.
2 List the Top 5 countries by population.
3 Calculate the average literacy rate.
4 List all countries having a literacy rate greater than 90%.
5 List all countries having an internet penetration greater than 70%.
6 List the Top 5 countries by GDP per capita.
7 Calculate the total population represented in the dataset.
8 Calculate the average internet penetration across all countries.
9 Identify the country having the highest number of internet users.
10 Find the correlation between Literacy Rate and Internet Penetration.
Hint:
Use the appropriate pandas statistical function.

In [64]:
# 1. Top 5 countries by GDP
print("1. Top 5 countries by GDP:")
print(merged_pop.nlargest(5, "GDP")[["country", "GDP"]])
print("___________________________________________________________________")
# 2.Top 5 countries by population
print("\n2. Top 5 countries by population:")
print(merged_pop.nlargest(5,"population")[["country","population"]])
print("___________________________________________________________________")
print("\n3. Calculate the average literacy rate")
print(merged_pop["literacy_rate"].mean())
print("___________________________________________________________________")
print("\n4. List all countries having a literacy rate greater than 90%")
print(merged_pop[merged_pop["literacy_rate"] >90])
print("___________________________________________________________________")

1. Top 5 countries by GDP:
         country       GDP
0  United States  30500000
1          China  19230000
4        Germany   4744000
2          India   4187000
3          Japan   4180000
___________________________________________________________________

2. Top 5 countries by population:
          country  population
1           China  1411778724
2           India  1380004385
0   United States   331002651
15      Indonesia   273523615
10         Brazil   212559417
___________________________________________________________________

3. Calculate the average literacy rate
97.248
___________________________________________________________________

4. List all countries having a literacy rate greater than 90%
           country  population       GDP  internet_users  literacy_rate  \
0    United States   331002651  30500000       312000000           99.0
1            China  1411778724  19230000      1080000000           97.2
3            Japan   125836021   4180000       118000000           99.0
4          Germany    83240525   4744000        79000000           99.0
5   United Kingdom    67886011   3839000        66000000           99.0
6           France    65273511   3211000        62000000           99.0
7            Italy    60461826   2420000        56000000           99.0
8           Canada    38005238   2250000        36000000           99.0
9        Australia    25687041   1880000        24000000           99.0
10          Brazil   212559417   2330000       181000000           93.2
11          Russia   145934462   2200000       125000000           99.7
12     South Korea    51780579   1800000        50000000           98.8
13           Spain    46754778   1710000        44000000           98.6
14          Mexico   128932753   1810000       102000000           95.4
15       Indonesia   273523615   1500000       212000000           96.0
16    Saudi Arabia    34813871   1100000        34000000           97.3
17          Turkey    84339067   1350000        69000000           96.7
18    South Africa    59308690    410000        43000000           95.0
19       Argentina    45195774    640000        41000000           99.1
20     Netherlands    17441139   1150000        17000000           99.0
21     Switzerland     8654622    940000         8500000           99.0
22          Sweden    10353442    650000        10100000           99.0
23          Norway     5421241    580000         5300000          100.0
24       Singapore     5850342    530000         5600000           97.5

    Internet Penetration (%)  GDP Per Capita
0                      94.26            0.09
1                      76.50            0.01
3                      93.77            0.03
4                      94.91            0.06
5                      97.22            0.06
6                      94.98            0.05
7                      92.62            0.04
8                      94.72            0.06
9                      93.43            0.07
10                     85.15            0.01
11                     85.65            0.02
12                     96.56            0.03
13                     94.11            0.04
14                     79.11            0.01
15                     77.51            0.01
16                     97.66            0.03
17                     81.81            0.02
18                     72.50            0.01
19                     90.72            0.01
20                     97.47            0.07
21                     98.21            0.11
22                     97.55            0.06
23                     97.76            0.11
24                     95.72            0.09
___________________________________________________________________

In [65]:
print("\n5. List all countries having an internet penetration greater than 70%")
print(merged_pop[merged_pop["Internet Penetration (%)"] >70])
print("___________________________________________________________________")

5. List all countries having an internet penetration greater than 70%
           country  population       GDP  internet_users  literacy_rate  \
0    United States   331002651  30500000       312000000           99.0
1            China  1411778724  19230000      1080000000           97.2
3            Japan   125836021   4180000       118000000           99.0
4          Germany    83240525   4744000        79000000           99.0
5   United Kingdom    67886011   3839000        66000000           99.0
6           France    65273511   3211000        62000000           99.0
7            Italy    60461826   2420000        56000000           99.0
8           Canada    38005238   2250000        36000000           99.0
9        Australia    25687041   1880000        24000000           99.0
10          Brazil   212559417   2330000       181000000           93.2
11          Russia   145934462   2200000       125000000           99.7
12     South Korea    51780579   1800000        50000000           98.8
13           Spain    46754778   1710000        44000000           98.6
14          Mexico   128932753   1810000       102000000           95.4
15       Indonesia   273523615   1500000       212000000           96.0
16    Saudi Arabia    34813871   1100000        34000000           97.3
17          Turkey    84339067   1350000        69000000           96.7
18    South Africa    59308690    410000        43000000           95.0
19       Argentina    45195774    640000        41000000           99.1
20     Netherlands    17441139   1150000        17000000           99.0
21     Switzerland     8654622    940000         8500000           99.0
22          Sweden    10353442    650000        10100000           99.0
23          Norway     5421241    580000         5300000          100.0
24       Singapore     5850342    530000         5600000           97.5

    Internet Penetration (%)  GDP Per Capita
0                      94.26            0.09
1                      76.50            0.01
3                      93.77            0.03
4                      94.91            0.06
5                      97.22            0.06
6                      94.98            0.05
7                      92.62            0.04
8                      94.72            0.06
9                      93.43            0.07
10                     85.15            0.01
11                     85.65            0.02
12                     96.56            0.03
13                     94.11            0.04
14                     79.11            0.01
15                     77.51            0.01
16                     97.66            0.03
17                     81.81            0.02
18                     72.50            0.01
19                     90.72            0.01
20                     97.47            0.07
21                     98.21            0.11
22                     97.55            0.06
23                     97.76            0.11
24                     95.72            0.09
___________________________________________________________________

In [66]:
print("\n6. List the Top 5 countries by GDP per capita")
print(merged_pop.nlargest(5,"GDP Per Capita")[["country","GDP Per Capita"]])
print("___________________________________________________________________")

6. List the Top 5 countries by GDP per capita
          country  GDP Per Capita
21    Switzerland            0.11
23         Norway            0.11
0   United States            0.09
24      Singapore            0.09
9       Australia            0.07
___________________________________________________________________

In [67]:
print("\n7. Calculate the total population represented in the dataset")
print(merged_pop["population"].sum())
print("___________________________________________________________________")

7. Calculate the total population represented in the dataset
4720039725
___________________________________________________________________

In [70]:
print("\n8. Calculate the average internet penetration across all countries")
print(merged_pop["Internet Penetration (%)"].mean())
print("___________________________________________________________________")
print("\n9. Identify the country having the highest number of internet users")
print(merged_pop[merged_pop["internet_users"]==merged_pop["internet_users"].max()][["country","internet_users"]])
print("___________________________________________________________________")
print("\n10. Find the correlation between Literacy Rate and Internet Penetration")
print(merged_pop["literacy_rate"].corr(merged_pop["Internet Penetration (%)"]))

8. Calculate the average internet penetration across all countries
89.6596
___________________________________________________________________

9. Identify the country having the highest number of internet users
  country  internet_users
1   China      1080000000
___________________________________________________________________

10. Find the correlation between Literacy Rate and Internet Penetration
0.77279756813985